### ISSUE TITLE
Keep pipeline consistent 

### ISSUE THREAD

**Issue by liamrussell125** [Clicksco/FSharpGuideLines#2]
https://github.com/Clicksco/FSharpGuideLines/pull/1

**Comment by TWith2Sugars** [comment]
https://github.com/Clicksco/FSharpGuideLines/pull/4

**Comment by TWith2Sugars** [comment]
From Liam

> The pipe is a list being passed through, my preference is to keep all operations on the pipeline to be of the initial data type.
